apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-test
spec:
  schedule: "* * 0 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: hello-world
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
